### ISSUE TITLE
[공지] 인증 뱃지 제출 요망

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#1]
본인의 뱃지 캡쳐본을 이메일로 보내주세요.  
2019.AI@rcv.sejong.ac.kr

그리고, 이메일 발송에 대한 여부를 본 이슈에 남겨주세요.

**Comment by socome** [comment]
![코드아카데미 캡쳐](https://user-images.githubusercontent.com/44772344/54071462-0bbb1c80-42b0-11e9-8a9b-5b0276764b0a.png)
![코드아카데미 캡쳐2](https://user-images.githubusercontent.com/44772344/54071464-0cec4980-42b0-11e9-86d1-9f5972deb2d1.png)

**Comment by KakyungLee** [comment]
@KakyungLee 이가경 학생 확인되었습니다.(from @unizard )

**Comment by LeeSemi** [comment]
![1](https://user-images.githubusercontent.com/48410602/54086187-8ce6e200-438a-11e9-8325-eb3842679911.PNG)
![2](https://user-images.githubusercontent.com/48410602/54086191-92442c80-438a-11e9-88ba-a28453fc9722.PNG)

**Comment by ghost** [comment]
@LeeSemi 이세미 학생 확인되었습니다. (from @unizard )

**Comment by lini1634** [comment]
이메일 보냈습니다

@lini1634  김해린 학생 확인되었습니다. (From @unizard )

**Comment by unizard** [comment]
@socome 김지원 학생 확인되었습니다. (From @unizard )

**Comment by unizard** [comment]
이현지 학생 확인되었습니다.

**Comment by unizard** [comment]
@big-chan 한대찬 학생 확인되었습니다.

**Comment by diakes** [comment]
이메일 보냈습니다. 

@diakes 김동익 학생 확인되었습니다. (From @unizard )

**Comment by rkdogo08** [comment]
이메일 보냈습니다

@rkdogo08 강산희 학생 확인되었습니다. (From @unizard )

**Comment by Jo-won** [comment]
이메일 보냈습니다

@Jo-won 조원 학생 확인되었습니다. (From @unizard )

**Comment by iammiori** [comment]
메일보냈습니다.

@iammiori 이미연 학생 확인되었습니다.

**Comment by unizard** [comment]
@Namhyunho 남현호 학생 확인되었습니다.

**Comment by Kwon-Yeong-Seo** [comment]
이메일 보냈습니다.

@Kwon-Yeong-Seo 권영서 학생 확인되었습니다. (From @unizard )

**Comment by Hongiee2** [comment]
이메일 보냈습니다.

@Hongiee2 김기홍학생 확인되었습니다. (From @unizard )

**Comment by 17011813** [comment]
이메일 보냈습니다~

**Comment by k-Yeonwoo** [comment]
이메일 보냈습니다

@k-Yeonwoo 김연우 학생 확인되었습니다.

**Comment by hahari22** [comment]
@diasy3277 이상민 학생 이메일로 다시 보내주세요. 이메일로 전달된거 없어요. (@unizard )

[image1.png]
[image2.png]
나의 iPhone에서 보냄

2019. 3. 12. 오후 8:07, k-Yeonwoo <notifications@github.com<mailto:notifications@github.com>> 작성:


이메일 보냈습니다

**Comment by BSH0420** [comment]
이메일 보냈습니다.

@BSH0420 백소현학생 다시 보내주세요. (@unizard )

**Comment by sezeom** [comment]
이메일 보냈습니다

@sezeom 이세정 학생 다시 보내주세요 (@unizard )

**Comment by zxas14** [comment]
이메일 보냈습니다.

@zxas14 김성빈학생 캡쳐영상 깨져서 왔어요. 다시 보내주세요.

**Comment by ruby-kim** [comment]
이메일 보냈습니다. (소프트웨어학과 김경남)

@kimkyeongnam 김경남학생 확인되었습니다.

**Comment by Eomdangyeong** [comment]
메일보냈습니다

**Comment by KYUUUW** [comment]
메일 송신 완료했습니다. (컴퓨터공학과 이규원)

**Comment by chldydgh4687** [comment]
메일 보냈습니다. (스마트기기 최용호)

**Comment by YEJIN325** [comment]
이메일 보냈습니다.

**Comment by sorachin** [comment]
메일 보냈습니다.

**Comment by xown3197** [comment]
메일 보냈습니다.

**Comment by min942773** [comment]
이메일 보냈습니다 (소프트웨어학과 김민주)

**Comment by glee1228** [comment]
인증뱃지 캡처 이메일 보냈습니다. (디지털콘텐츠학과 이동훈)

**Comment by kaynsion** [comment]
이메일 보냈습니다. (스마트기기공학 김재형)

**Comment by aaliyahee** [comment]
이메일 보냈습니다 (무인이동체공학 황태희)

**Comment by 17011775** [comment]
이메일 보냈습니다(스마트기기 김남규)

**Comment by Seeun-Lim** [comment]
이메일 보냈습니다(컴퓨터공학과 임세은)

**Comment by hahari22** [comment]
이메일 보냈습니다 (무인이동체공학 이상민)

**Comment by LIMJIY00N** [comment]
이메일 보냈습니다(컴퓨터공학과 임지윤)

**Comment by Junuu** [comment]
이메일 보냈습니다 (디지털콘텐츠학과 김준우)

**Comment by PMH2906** [comment]
17011757 박미희 이메일 보냈습니다.

**Comment by minju0702** [comment]
17011820 송민주 이메일 보냈습니다

**Comment by nhk9680** [comment]
17011832 김남훈 이메일 보냈습니다.

**Comment by jiin0217** [comment]
이메일 보냈습니다(디지털 콘텐츠학과 유지인)

**Comment by smileeeey** [comment]
16010960 이수민이메일 보냈습니다!

**Comment by joooooonie** [comment]
이메일 보냈습니다 (17011870 박준희)

**Comment by joooooonie** [comment]
17011870 박준희 이메일 보냈습니다.

**Comment by hyj378** [comment]
황유진 이메일 보냈습니다.

**Comment by unizard** [comment]
| 이름 | P/F | 기타
-- | -- | -- | --
1 | 강산희 | P |  
2 | 권영서 | P |  
3 | 김경남 | P |  
4 | 김기흥 | P |  
5 | 김남규 | P |  
6 | 김남훈 | P |  
7 | 김동익 | P |  
8 | 김민주 | P |  
9 | 김성빈 | P |  
10 | 김연우 | P |  
11 | 김재형 | P |  
12 | 김준우 | P |  
13 | 김지원 | P |  
14 | 김태주 | P |  
15 | 김학주 | P |  
16 | 김해린 | P |  
17 | 남현호 | P |  
18 | 노윤아 | P |  
19 | 박미희 | P |  
20 | 박준희 | F | 뱃지부족, 다시 제출
21 | 백소현 | P |  
22 | 서예진 | P |  
23 | 손창우 | P |  
24 | 엄단경 | P |  
25 | 위성민 | F | 미제출, 제출 요망
26 | 유지인 | P |  
27 | 유지인 | P |  
28 | 이규원 | P |  
29 | 이동훈 | P |  
30 | 이미연 | P |  
31 | 이상민 | P |  
32 | 이상민 | P |  
33 | 이세미 | P |  
34 | 이세정 | P |  
35 | 이수민 | P |  
36 | 이주혁 | P |  
37 | 이지연 | P |  
38 | 이현지 | P |  
39 | 임세은 | P |  
40 | 임지윤 | P |  
41 | 조원 | P |  
42 | 진소라 | P |  
43 | 진소라 | P |  
44 | 최용호 | P |  
45 | 최지연 | P |  
46 | 한대찬 | P |  
47 | 황유진 | P |  
48 | 황정현 | P |  
49 | 황태희 | P |
