### ISSUE TITLE
[추천동영상] 딥러닝 꼭 써야하나요?

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#10]
여러분 안녕하세요. 
3월 둘쨰주 주말 스벅에 앉아서 고민을 하다가, 여러분에게 추천해주고 싶은 동영상이 있어 링크를 공유 해 드립니다. 정자세로 듣지 않으셔도 좋습니다. 대중교통안에서 잠자기 전 가볍게 시청해보세요. 피가되고 살이 될겁니다. 😋

### 추천 동영상
- [딥러닝 꼭 써야하나요?](https://www.youtube.com/watch?v=MSWCQ9lRA1Y)
- [딥러닝의 실제적용, 튜토리얼과 무엇이 다른가?](https://www.youtube.com/watch?v=daTqajvdeTw), (4분부터~)

**Comment by Namhyunho** [comment]
감사합니다!👍

2019년 3월 16일 (토) 오후 2:36, Yukyung Choi <notifications@github.com>님이 작성:
