### ISSUE TITLE
[공지] 텀프로젝트 논문 양식 첨부

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#105]
## 양식 공유
- [텀프로젝트_논문양식.zip](https://github.com/unizard/2019.Spring.AI/files/3281309/_.zip)
- 본 양식은 국내학술대회의 양식입니다. 
- 함께 넣어둔 참고 논문의 포멧으로 작성하여 제출하시면 됩니다.

**Comment by hahari22** [comment]
교수님
보고서 작성중인데 분량 제한이 있나요???

**Comment by unizard** [comment]
보통 6장입니다. 분량이 더 필요한가요?

2019년 6월 21일 (금) 오후 6:56, diasy3277 <notifications@github.com>님이 작성:
