### ISSUE TITLE
[추천동영상] 대학원 꼭 가야 하나요? 

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#11]
> 3학년, 4학년으로 구성된 인공지능 수업에는 **대학원**을 고민중일 친구들이 있을지도 모른다는 생각이 들었습니다. 본 동영상 역시 대중교통안에서 잠자기전 가벼운 마음으로 시청해보세요~😛

### 동국대 홍정모 교수님
- [좋은 엔지니어가 되려면 꼭 대학원에 가야 하나요?](https://www.youtube.com/watch?v=HV2oGR9E6Ss)

### 뼈아대
- [대학원 가기전] [대학원은 누가 가는가?](https://www.youtube.com/watch?v=fURfN-Lm4Yw)
- [대학원 생활중] [대학원 생활은 무엇인가?](https://www.youtube.com/watch?v=HV2oGR9E6Ss)
- [대학원 졸업후] [대학원 졸업, 그리고 취업](https://www.youtube.com/watch?v=VlOA7Pj-9o0)

### 엄태웅연구원님, 최윤섭연구원님, 권창현 교수님
- [작가3인방의 글이 모아진 블로그](http://gradschoolstory.net/)
- [대학원생때 알았더라면 좋았을 것들, 오프라인 모임](https://www.youtube.com/watch?v=RHghh72SRuE&list=PL0oFI08O71gLW142VvCK0yxuKmtLR-ESn&index=8)

### 좋은 지도교수 
- [대학원과 지도교수 ‘똑똑하게’ 고르는 법](https://news.samsung.com/kr/%EB%8C%80%ED%95%99%EC%9B%90%EA%B3%BC-%EC%A7%80%EB%8F%84%EA%B5%90%EC%88%98-%EB%98%91%EB%98%91%ED%95%98%EA%B2%8C-%EA%B3%A0%EB%A5%B4%EB%8A%94-%EB%B2%95)

> 최종 판단은 본인의 몫입니다. 결정을 하기 전에 다양한 의견을 들어보는 것은 좋습니다. 다양한 의견을 들어볼 때 검증된 분들의 의견을 듣는것이 좋을 것이라 생각이 들어 공유합니다.

**Comment by chldydgh4687** [comment]
오우..교수님 신경써주셔서 감사합니다.. : )

**Comment by glee1228** [comment]
정말 감사합니다. 잘 보겠습니다.. 👍
