### ISSUE TITLE
[공지] 텀프로젝 발표 시간 (선착순)

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#115]
### 10분 발표 + 5분 질의응답
- 10분 발표 넘어가면 마이크가 꺼집니다.

시간 | 팀명 | 텀플주제 
--: | :--: | :--: | 
6:00-6:15 |  페이스타임 |  표정분류기 
6:15-6:30 |  인공준희  |  수화분류기 
6:30-6:45 | aicoco  | 꽃분류기  
6:45-7:00 | 기레기통   |  낚시성기사분류기 
7:00-7:15 | 리사이클   |  재활용품분류기 |  
7:15-7:30 |  AI대장   |  랜드마크분류기  |  
7:30-7:45 |  작위적인공조 |  음식추천분류기 |  
7:45-8:00 |   소웨지존  | 이모티콘 추천 분류기
8:00-8:15 | 휴학과 자퇴사이  |  장애물분류 |  
8:15-8:30 | 분류지렷죠 | 질병분류기 |

**Comment by ruby-kim** [comment]
**1조 소웨지존** 7:45-8:00으로 하겠습니다.

**Comment by nhk9680** [comment]
6조 휴학과 자퇴사이 8:00 하겠습니다.

**Comment by sorachin** [comment]
10조 작위적인공조 7시 30분 하겠습니다.

**Comment by Namhyunho** [comment]
3조 AI_leader(AI대장) 7시15분 하겠습니다.

**Comment by rjhwang08** [comment]
8조 기레기통 6:45-7:00 하겠습니다

**Comment by iammiori** [comment]
2조 인공준희 6시 15분 - 6시30분 하겠습니다

**Comment by 17011775** [comment]
9조 리사이클 7시 하겠습니다

**Comment by 17011813** [comment]
4조 aicoco 6:30 하겠습니다

**Comment by unizard** [comment]
자동으로 5조 페이스타임이 6시 발표네요...
