### ISSUE TITLE
[공지] 텀프로젝트 Repository를 Sejong AI Research 에 transfer 하는  방법

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#118]
### 2. 텀프로젝트 작업 중인 Repository => Settings => (맨마지막) Transfer 

![image](https://user-images.githubusercontent.com/11758940/59975631-33cb5300-95f5-11e9-9ebc-cec1f2a594f0.png)

- 아래의 첫번째 줄에 현 Repository 의 이름
- 아래의 두번째 줄에 sejongresearch 를 입력한다.
![image](https://user-images.githubusercontent.com/11758940/59975638-45acf600-95f5-11e9-8e09-c28c683edaf4.png)

### 3.  이전 완료 확인
- https://github.com/sejongresearch 에서 확인

**Comment by Hongiee2** [comment]
교수님 transfer하려는데 이렇게 뜨는데 뭐가 문제인걸까요ㅠㅠㅠ
 
 
-----Original Message-----

**Comment by Hongiee2** [comment]
아앗 조인해서 해결했습니다!!ㅎㅎㅎ
 
죄송합니다~~!!
 
 
-----Original Message-----
