### ISSUE TITLE
[추천동영상] 당신이 뽑히지 않는 이유?!

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#12]
> 제목부터 자극적인가요! 하지만, 사실을 직면하고 자극이 필요하신 분이 있다면 한번 쯤 들어보세요.

### 뼈아대
- [당신이 뽑히지 않은 이유?!](https://www.youtube.com/watch?v=3eJzpEwMYos)

**Comment by zxas14** [comment]
영상 올려주셔서 감사합니다.
