### ISSUE TITLE
[숙제] 이론 수업 확률 숙제 

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#14]
데드라인: 3월 21일까지

**Comment by Jo-won** [comment]
이메일로 보냈습니다

**Comment by 17011813** [comment]
이메일 확인 부탁드려요

**Comment by KYUUUW** [comment]
컴퓨터공학과 이규원 이메일 발송 완료했습니다!

**Comment by joooooonie** [comment]
이메일 보냈습니다. -스마트기기 17011870 박준희

**Comment by k-Yeonwoo** [comment]
이메일 보냈습니다-스마트기기 17011780 김연우

**Comment by rjhwang08** [comment]
이메일 보냈습니다. 스마트기기 17011827 황정현

**Comment by PMH2906** [comment]
이메일 보냈습니다. 무인이동체 17011757 박미희

**Comment by Eomdangyeong** [comment]
메일보냈습니다. 17011811엄단경

**Comment by Junuu** [comment]
메일로 보냈습니다. 16011170 김준우

**Comment by jiin0217** [comment]
메일 보냈습니다.(디지털콘텐츠학과 유지인)

**Comment by smileeeey** [comment]
메일 보냈습니다! 컴퓨터공학과 16010960 이수민

**Comment by ruby-kim** [comment]
이메일 보냈습니다 (소프트웨어학과 김경남)

**Comment by lini1634** [comment]
보냈습니다 -무인17011755김해린

**Comment by big-chan** [comment]
제출했습니다

**Comment by Kwon-Yeong-Seo** [comment]
이메일 보냈습니다 (무인이동체 권영서)

**Comment by sorachin** [comment]
이메일 보냈습니다. 디지털컨텐츠 진소라

**Comment by rkdogo08** [comment]
메일 보냈습니다. 무인이동체 강산희

**Comment by kaynsion** [comment]
메일 보냈습니다. 17011829 김재형 스마트기기공학

**Comment by chldydgh4687** [comment]
이메일 보냈습니다. 17013253 최용호 스마트기기공학

**Comment by Namhyunho** [comment]
메일 보냈습니다. 17013249 남현호 무인이동체

**Comment by sezeom** [comment]
메일 보냈습니다. -17011850 스마트기기 이세정

**Comment by diakes** [comment]
메일 보냈습니다 컴퓨터공학 김동익

**Comment by nhk9680** [comment]
메일 보냈습니다. - 스마트기기 김남훈

**Comment by xown3197** [comment]
메일 보냈습니다 - 무인이동체 김태주

**Comment by hahari22** [comment]
메일 보냈습니다. -무인이동체  이상민

**Comment by socome** [comment]
메일 보냈습니다.

**Comment by Seeun-Lim** [comment]
이메일 보냈습니다.-컴퓨터공학과 임세은

**Comment by iammiori** [comment]
제출했습니다. [지능기전공학부 이미연]

**Comment by LIMJIY00N** [comment]
이메일 보냈습니다. 컴퓨터공학과 임지윤

**Comment by Hongiee2** [comment]
이메일 보냈습니다. 컴퓨터공학과 김기홍

**Comment by aaliyahee** [comment]
이메일 보냈습니다 (무인이동체 황태희)

**Comment by 17011775** [comment]
이메일 보냈습니다(스마트기기 김남규)

**Comment by BSH0420** [comment]
이메일 보냈습니다! (스마트기기 백소현)

**Comment by Hongiee2** [comment]
이메일 보냈습니다. 컴퓨터공학과 이가경

**Comment by KakyungLee** [comment]
이메일 보냈습니다. 컴퓨터공학과 이가경

**Comment by minju0702** [comment]
이메일 보냈습니다! 무인이동체공학과 송민주

**Comment by zxas14** [comment]
이메일 보냈습니다. 스마트기기전공 김성빈

**Comment by unizard** [comment]
> 제출여부 확인 부탁드립니다.
> 현재, 서예진, 이지연 미제출 / 이가경 첨부 없음 입니다.

번호 | 이름 | 제출여부
-- | -- | --
1 | 강산희 | 제출
2 | 권영서 | 제출
3 | 김경남 | 제출
4 | 김기홍 | 제출
5 | 김남규 | 제출
6 | 김남훈 | 제출
7 | 김동익 | 제출
8 | 김민주 | 제출
9 | 김성빈 | 제출
10 | 김연우 | 제출
11 | 김재형 | 제출
12 | 김준우 | 제출
13 | 김지원 | 제출
14 | 김태주 | 제출
15 | 김학주 | 제출
16 | 김해린 | 제출
17 | 남현호 | 제출
18 | 노윤아 | 제출
19 | 박미희 | 제출
20 | 박준희 | 제출
21 | 백소현 | 제출
22 | 서예진 | 미제출
23 | 손창우 | 제출
24 | 송민주 | 제출
25 | 엄단경 | 제출
26 | 위성민 | 제출
27 | 유지인 | 제출
28 | 이가경 | 미제출
29 | 이규원 | 제출
30 | 이동훈 | 제출
31 | 이미연 | 제출
32 | 이상민 | 제출
33 | 이세미 | 제출
34 | 이세정 | 제출
35 | 이수민 | 제출
36 | 이주혁 | 제출
37 | 이지연 | 미제출
38 | 이현지 | 제출
39 | 임세은 | 제출
40 | 임지윤 | 제출
41 | 조원 | 제출
42 | 진소라 | 제출
43 | 최용호 | 제출
44 | 최지연 | 제출
45 | 한대찬 | 제출
46 | 황유진 | 제출
47 | 황정현 | 제출
48 | 황태희 | 제출
