### ISSUE TITLE
[참고] 머신러닝에 대한 매우 쉬운 설명 from terry

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#19]
- Terry 의 머신러닝에 대한 매우 쉬운 설명!! 
https://www.youtube.com/watch?v=mqaATsYP6j0
> 좋네요 ㅎ

**Comment by Namhyunho** [comment]
항상 감사합니다!😊

2019년 3월 23일 (토) 오후 7:42, Yukyung Choi <notifications@github.com>님이 작성:
