### ISSUE TITLE
[모집] 텀프로젝트 팀원 모집합니다. 

### ISSUE THREAD

**Issue by socome** [unizard/2019.Spring.AI#20]
안녕하세요. 항공우주공학전공 김지원입니다. 

이번 텀프로젝트를 진행할 팀원을 모집합니다. 

현재는 

항공우주공학전공 김지원
무인이동체전공 남현호

이렇게 총 2명이입니다. 

저희는 최대한 다양한 학과로 팀원을 구성해 다양한 전공지식이 융합된 프로젝트를 진행하고 싶습니다.

다양한 전공지식을 기반으로 인공지능 텀프로젝트를 함께 수행하실 분들은 댓글이나 메일 부탁드립니다.

메일은socome@sju.ac.kr  입니다.  

-------------------------- 현재 모집완료됐습니다.

**Comment by unizard** [comment]
@ALL 이렇게 다양한 과로 구성된 프로젝트 팀! 대 환영합니다.
