### ISSUE TITLE
[공지] 실습 관련 Q&A 및 요청사항

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#23]
### 꼭 Colab 만 사용해야 하나요?
- 개발환경 구축에 익숙하지 않은 친구들은 코랩을 사용하세요. 여러분의 삽질 시간을 줄여줍니다.

### 개인 노트북에 개발환경 구축해서 사용하고 싶습니다. 괜찮나요?
- 네, 본인의 노트북에 개발환경을 구축해서 사용하셔도 좋습니다.
- 그러나 그에 따른 예외사항은 본인이 직접 해결하셔야 합니다.

**Comment by unizard** [comment]
@ALL 실습관련 기타 질문은 이쪽으로 코멘트 부탁드립니다.

**Comment by Namhyunho** [comment]
수업시간에 받았던 질문 입니다. 
------------------------------------------------------------------
x_data = xy[ : , 1:-1]  <- 배추가격 문제에서 

1. 여기서 " , "  가 왜 있는 건가요?
2. 그리고 [  1 : -1 ] 이 의미하는 의미가 뭔가요?

1번의 답변 
[ 행(rows) , 열(columns)]을 의미합니다. 

2번의 답변 
저 표현은 python의 Slicing 개념입니다.
배추가격의 데이터는 [2922 rows x 6 columns]로 이루어져 있습니다.  (2922행 6열)
그중 [  :  , 1:-1 ] 이면 
[모든행 , 열중 처음 두열과 마지막 한열을 제외]
에 해당하는 데이터를 사용하겠다는 의미입니다.

![slicing](https://user-images.githubusercontent.com/48246523/55667037-2de59180-5892-11e9-8090-388e5d372eec.PNG)

-----------------------------------------------------------------------
W = tf.Variable(tf.random_normal([2, 1]), name="weight")  <- 실습코드중 

1. tf.random_normal([2, 1]) ]  여기서 [2, 1]이 의미가 뭔가요?? 

[ a , b , c ...] -> " , "가 하나씩 늘어나면서  공간이(차원) 하나씩 늘어난다고 생각하시면 편할 것 같습니다.
[ 2 , 1 ] 에기서 1은 하나의 요소로 이루어진 벡터이고 2는 요소가 1개인 벡터가 2개로 이루어진 행렬이 됩니다.  그렇다면 [2, 2 ,1 ]이면 어떻게 될까요? 
요소가 1개인 벡터가 2개인 행렬이 2개로 나타날 것입니다.  
---------------------------------------------------------------------------
![예시2](https://user-images.githubusercontent.com/48246523/55667014-a009a680-5891-11e9-8b81-6f39c78104f0.PNG)
![예시3](https://user-images.githubusercontent.com/48246523/55667016-a26c0080-5891-11e9-977e-b637b35416ef.PNG)

저의 기억에 남았던 질문들만 정리해서 올렸습니다.
