### ISSUE TITLE
[공지] 텀 프로젝트 관련 Q&A 모음

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#24]
### 팀은 4명으로 구성해도 되나요?
- 4~5명이 표준입니다.
- 몇몇 팀은 4명으로 구성하셔도 됩니다. 일단 4명이 모이셨으면 알려주세요.

### 텀 프로젝트 가이드 라인이 있나요?
- 주제만 맞으면 됩니다. 주제는 "분류기" 만들기 입니다.
- 어떤 분류기를 만드셔도 좋습니다.
- 분류기를 만드는데 필요하면, 각종 데이터 가공 및 각종 라이브러리 사용 모두 허용됩니다.
- 물체검출을 위한 SSD, Yolo 사용되나요? 네 가능합니다.

### 텀 프로젝트 결과물은 어떻게 제출되나요?
- 코드와 리포트로 제출됩니다.
- 리포트는 영문 혹은 국문으로 제출하시면 되나, 템플릿이 제공됩니다.
- Two Column 6장~8장으로 작성하시면 됩니다.
- 스탠포드 수업에서 텀 프로젝트 리포트 작성된 예시를 공유드리오니 참고하세요.
  - http://cs231n.stanford.edu/2017/reports.html

### GPU지원 해주시나요?
- 주제에 따라서 GPU가 반드시 필요하다고 교수님의 판단이 들경우 제공해 드릴 예정이며 수요조사도 할 예정입니다.
- GPU서버는 카카오브레인에서 지원해주실 예정입니다.

**Comment by unizard** [comment]
@All 텀프로젝트 관련 기타 질문은 본 이슈로 코멘트 부탁드립니다.

**Comment by Hongiee2** [comment]
텀프로젝트 관련 질문드립니다!

여쭤보기 조심스러운 질문이다만, 주제선정시 고려해야할 사안인 것 같아서 문의드립니다.

대략적으로라도 프로젝트 평가 기준들을 알고싶습니다.

아이디어, 가설 검증, 사용기술, 구현 등 어느부분에 주안점을 두고 진행해야할지 파악하고자 말씀드립니다.

감사합니다!

**Comment by unizard** [comment]
@Hongiee2  아이디어, 가설 검증, 사용기술, 구현 모듬 부분이 평가 항목입니다. 평가기준을 수업첫날 언급했었는데, 다시 한번 이야기 하자면 다음과 같습니다. 교수평가(외부평가위원포함)와 동료평가(팀간평가+팀내평가)가 동시에 이루어집니다. 이정도면 답변이 되었는지 모르겠네요. 주제 선정에 어려움이 있다면 찾아오세요.

**Comment by hahari22** [comment]
교수님!
최종 발표는 조원 모두 참여하여 발표하는 것인가요?
