### ISSUE TITLE
[공지] 선형회귀 과제 

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#27]
## 배추 가격 예측하는 AI머신 만들기
> 아래의 코드는 바로 실행되지 않습니다. 반드시 ?? 부분을 직접 채우셔야 합니다.
- [학습용코드](https://colab.research.google.com/drive/1dXMgQXRc6DSIR8A5XtqC2s6J0vCiHhAF)
- [예측용코드](https://colab.research.google.com/drive/1RfI9VhtobFJXuH8AbwV6DUa5aujB0tTn)

## 본 과제를 통해 익히고자 하는 내용
> 셀프 체크 리스트
- [ ] 텐서플로우를 이용한 선형 회귀 문제 푸는 법
- [ ] 텐서플로우로 파일 로드 하는 법 확인하기
- [ ] 텐서플로우로 학습 모델 저장하는 법 확인하기
- [ ] 텐서플로우로 학습한 모델 로드하는 법 확인하기

## 과제 수행 방법
- Colab 사본을 만들어 본인의 구글 드라이브에 저장합니다.
- 학습용코드와 예측용코드에 **??** 로 설정된 부분에 코드를 채웁니다.
- 학습용코드를 통해 모델 학습을 진행합니다.
- 예측용코드를 실행하며, 아래의 평균 온도, 최저 온도, 최고 온도, 강수량을 입력하여 얻은 배추가격을 메일로 보냅니다.   
>> 평균 온도: -2.7
>> 최저 온도: -6.6
>> 최고 온도: 2.0
>> 강수량:  0.1
[당신이 얻은 정답은?]

## 과제 제출 방법
- 이메일을 통해 제출할 내용
  - 완성된 코드 2개
  - 예상되는  배추 가격 

## 퀴즈 공지
- 본 코드를 기준으로 실습 퀴즈가 진행됨을 미리 알려드립니다. 
- 과제를 통한 코드 이해 꼭! 부탁드립니다.

**Comment by unizard** [comment]
- Colab에서 개인 구글 드라이브를 이용한 학습 모델 저장 및 로드 방법은 여러분의 텀프로젝트를 진행시에도 유용하게 사용 가능합니다. 
- 단순히, 비어있는 코드부분만 채우지 마시고, 전체적인 코드 내용을 숙지하시기 바랍니다.
- 단원이 마칠때마다 코랩을 이용한 실습이 진행됩니다.  지금부터 한단계씩 익숙해지시기 바랍니다.

**Comment by ruby-kim** [comment]
이메일 보냈습니다. (소프트웨어학과 김경남)

**Comment by glee1228** [comment]
이메일 보냈습니다 (디지털콘텐츠학과 이동훈)

**Comment by min942773** [comment]
이메일 보냈습니다. (소프트웨어학과 김민주)

**Comment by hahari22** [comment]
이메일 보냈습니다.(무인이동체 이상민)

**Comment by Namhyunho** [comment]
17013249 남현호

2019년 3월 30일 (토) 오후 7:24, Yukyung Choi <notifications@github.com>님이 작성:

**Comment by Namhyunho** [comment]
이메일 보냈습니다.(무인이동체 남현호)

**Comment by iammiori** [comment]
이메일 보냈습니다. (무인이동체 이미연)

**Comment by sorachin** [comment]
메일 보냈습니다. (디지털컨텐츠 진소라)

**Comment by 17011813** [comment]
메일 보냈습니다(스마트기기 노윤아)

**Comment by rjhwang08** [comment]
메일 보냈습니다. (17011827 스마트기기 황정현)

**Comment by jiin0217** [comment]
메일보냈습니다.(디지털콘텐츠학과 유지인)

**Comment by xown3197** [comment]
메일 보냈습니다.(무인이동체공학과 김태주)

**Comment by Hongiee2** [comment]
이메일 보냈습니다 (컴퓨터공학 김기홍)

**Comment by KakyungLee** [comment]
이메일 보냈습니다.(컴퓨터공학과 이가경)

**Comment by k-Yeonwoo** [comment]
이메일 보냈습니다 (스마트기기공학과 김연우)

**Comment by minju0702** [comment]
메일 보냈습니다. (무인이동체공학과 송민주)

**Comment by PMH2906** [comment]
이메일 보냈습니다.(무인이동체공학과 박미희)

**Comment by zxas14** [comment]
이메일 보냈습니다.(스마트기기 전공 김성빈)

**Comment by BSH0420** [comment]
이메일 보냈습니다. (스마트기기 17011830 백소현)

**Comment by rkdogo08** [comment]
메일 보냈습니다.(무인이동체공학 강산희)

**Comment by chldydgh4687** [comment]
이메일 보냈습니다.(스마트기기공학과 최용호)

**Comment by diakes** [comment]
이멜일 보냈습니다.(컴퓨터공학과 김동익)

**Comment by joooooonie** [comment]
이메일 보냈습니다 (스마트기기공학전공 박준희)

**Comment by KYUUUW** [comment]
이메일 보냈습니다. (컴퓨터공학과 이규원)

**Comment by LIMJIY00N** [comment]
이메일 보냈습니다. (컴퓨터공학과 임지윤)

**Comment by 17011775** [comment]
메일 보냈습니다(스마트기기 김남규)

**Comment by sezeom** [comment]
이메일 보냈습니다. (스마트기기 이세정)

**Comment by Junuu** [comment]
이메일 보냈습니다.(디지털콘텐츠 김준우)

**Comment by LIMJIY00N** [comment]
이메일 보냈습니다. (컴퓨터공학과 임지윤)

**Comment by smileeeey** [comment]
이메일 보냈습니다(컴퓨터공학과 이수민)

**Comment by Kwon-Yeong-Seo** [comment]
이메일 보냈습니다 (무인이동체공학과 권영서)

**Comment by nhk9680** [comment]
이메일 보냈습니다. (스마트기기공학 김남훈)

**Comment by aaliyahee** [comment]
이메일 보냈습니다 (무인이동체 황태희)

**Comment by unizard** [comment]
| 성명 | 제출여부
-- | -- | --
1 | 강산희 | O
2 | 권영서 | O
3 | 김경남 | O
4 | 김기홍 | O
5 | 김남규 | O
6 | 김남훈 | O
7 | 김동익 | O
8 | 김민주 | O
9 | 김성빈 | O
10 | 김연우 | O
11 | 김재형 | O
12 | 김준우 | O
13 | 김지원 | O
14 | 김태주 | O
15 | 김해린 | O
16 | 남현호 | O
17 | 노윤아 | O
18 | 박미희 | O
19 | 박준희 | O
20 | 백소현 | O
21 | 서예진 | O
22 | 손창우 | O
23 | 송민주 | O
24 | 엄단경 | O
25 | 위성민 | O
26 | 유지인 | O
27 | 이가경 | O
28 | 이규원 | O
29 | 이동훈 | O
30 | 이미연 | O
31 | 이상민 | O
32 | 이세미 | O
33 | 이세정 | O
34 | 이수민 | O
35 | 이주혁 | O
36 | 이현지 | O
37 | 임세은 | O
38 | 임지윤 | O
39 | 조원 | O
40 | 진소라 | O
41 | 최용호 | O
42 | 최지연 | O
43 | 한대찬 | O
44 | 황유진 | O
45 | 황정현 | O
46 | 황태희 | O

**Comment by Namhyunho** [comment]
다음 항목을 공유했습니다.

인공지능 CNN 퀴즈 문제_남현호.ipynb
https://colab.research.google.com/drive/1C0VOrdfzpQutbvTUywkwaALWtqY4bC5h?ts=5cdce104

첨부파일이 아닌 온라인 저장 파일입니다. 항목을 열려면 위의 링크를  
클릭하세요.

인공지능퀴즈
