### ISSUE TITLE
[공지] 텀프로젝트 주제 선정 요망

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#3]
## 팀 프로젝트 명단 정보

번호 | 팀명 | 주제 | 팀원
-- | -- | -- | --
1 | 소웨지존 | 이모티콘 추천 분류기 | **김경남**, 김민주, 유지인, 이주혁, 황유진
2 | 인공준희 | [수화분류기](https://github.com/Jo-won/A.I-Term-project) | **조원**, 박준희, 이규원, 이미연, 한대찬
3 | AI대장 | 랜드마크 분류기 | **이수민**, 김지원, 남현호, 이동훈, 김준우
4 | aicoco | 꽃분류기 | **박미희**, 이세미, 노윤아, 김해린, 엄단경
5 | 페이스타임 | 표정분류기 | **김연우**, 송민주, 백소현, 이세정
6 | 자퇴와휴학사이 | 장애물분류기 | **위성민**, 최용호, 권영서, 김남훈, 강산희
7 | 분류지렸죠 | 4/10예정 | **김기홍**, 김동익, 이가경, 이상민
8 | 미정 | 뉴스 기사 분류기 | **최지연**, 황정현, 서예진, 김재형, 이현지
9 | 미정 | 미정 | **김남규**, 김성빈, 임지윤, 임세은
10 | 작위적인공조 | 미정 | **손창우**, 김태주, 황태희, 진소라

**Comment by ruby-kim** [comment]
## [팀1] [수정]주제: 자연어처리를 통해 채팅의 분위기에 맞는 이모티콘 추천 분류기
이모티콘은 주석으로 달아놓은 상태에서 문장을 미리 설정해 놓은 클래스로 분류하고.  
클래스에 맞는 이모티콘을 추천하는 AI분류기를 만들 예정입니다.

### 팀명 : 소웨지존

### 팀원
>김경남(소프트웨어학과)
김민주(소프트웨어학과)
유지인(디지털콘텐츠학과)
이주혁(소프트웨어학과)
황유진(지능기전공학부 무인이동체공학)

### 코멘트
19.03.31
@kimkyeongnam 
옷 분류기 역시 데이터 셋이 쉽지 않겠네요. 어떤 계획을 가지고 있죠? (from @unizard)

현재 네이버 스마트 렌즈에도 쇼핑렌즈라는 이름으로 들어가 있어요. 
작년 Deview 2018 에서 관련 연구가 발표되기도 했습니다. 
물론 분류기라기 보다는 Image Retrieval에 가깝구요. 
다음의 동영상을 참고해보세요 https://tv.naver.com/v/4580038

<br>
@unizard 
조원들과 논의 결과 주제를 수정하기로 결정했습니다.<br>
한번만 더 피드백 해주시면 감사하겠습니다 :-)

---
19.04.01 
@kimkyeongnam 
대분류기를 하기로 했군요. 주제 좋습니다. 
여기서 또 이제 이런 질문으로 이어지죠.
그럼 어떤 카테고리를 분류하실겁니까? 그 카테고리 종류는 어떻게 정하실꺼죠?
(생각의 흐름을 잘 따라와 보세요. 실제 현업에서 했던 고민들을 이야기 할겁니다.)

<br>
@unizard 

* **대분류**: 교육,학문 / 여행 / 건강 / 스포츠 / 음식 / 패션
* **소분류**
   * [교육,학문] 수학, 역사, 과학, 심리학... 
   * [여행] 국내여행, 해외여행
   * [건강] 운동, 식생활&식습관...
   * [스포츠] 육상, 수상..
   * [음식] 한식, 양식, 중식  
   * [패션] 상의, 바지, 스커트, 원피스&세트..

현재는 이런식으로 정하려고 합니다.
세부사항은 좀 더 의논해야 할 것 같은데, 빠른시일 내에 토론 후 올리도록 하겠습니다.

<br>
@kimkyeongnam 

머리 속에 떠오르는 분류를 기준으로 삼을 경우 해당 카테고리에 대한 데이터셋을 구하기 어려운 경우가 많아요. 예를들어 교육, 학문이란 데이터 셋은 참 개념적이네요 ㅎㅎ
데이터 셋 카테고리는 어떻게 정하는가? 에 대한 답으로 ImageNet 데이터셋의 1000개의 Class 가 어떻게 정해졌는지를 한번 알아보면 됩니다.

직접 데이터 셋을 촬영하거나 크롤링하는 것도 좋지만, 지금은 공부하는 과정이니 최대한 공개된 데이터셋을 활용하면 좋습니다.

아래의 구글 데이터셋을 분석해보고 
https://storage.googleapis.com/openimages/web/index.html

여러 개의 클래스를 상위 클래스로 묶어 대분류기를 만들면 좋을겁니다.
즉, 트리 형태의 분석을 통해 중간 쯤 해당하는 레이어의 분류 기준을 활용하면 아주 나이스 하게 문제를 풀수 있을 겁니다. 

물론 여러분의 팀이 원하는 분류가 아니라면? 직접 촬영하거나 아님 다른 공개 데이터 셋을 찾아야 겠쬬?

---

19.04.04
@unizard 상담한 내용을 바탕으로 주제 수정했습니다! :-)

**Comment by iammiori** [comment]
## [팀2] 주제:  수화분류

> 팀명: 인공준희

## 역할

> **팀장: 17011822 조원 (지능기전공학부 스마트기기공학)**
> **팀명: 17011870 박준희 (지능기전공학부 스마트기기공학)**
> 팀원1: 15010815 이규원(컴퓨터공학과)
> 팀원2: 17011879 이미연 (지능기전공학부 무인이동체공학)
> 팀원3: 17011883 한대찬 (지능기전공학부 스마트기기공학)

**Comment by smileeeey** [comment]
### [팀3] 주제: 세종대학교 랜드마크 분류기

**팀명: AI대장**

16010960 이수민(컴퓨터공학과)  ((팀장))
14011615 김지원(항공우주공학전공)
17013249 남현호(지능기전공학부 무인이동체공학)
13011186 이동훈(디지털콘텐츠학과)
16011170 김준우(디지털콘텐츠학과)

**Comment by PMH2906** [comment]
## [팀4] 주제: 꽃분류기

### 팀명:  aicoco
<br>

- 팀장
  - 17011757 박미희(지능기전공학부 무인이동체공학)
- 팀원
  - 17011862 이세미(지능기전공학부 스마트기기공학)
  - 17011813 노윤아(지능기전공학부 스마트기기공학)
  - 17011755 김해린(지능기전공학부 무인이동체공학)
  - 17011811 엄단경(지능기전공학부 무인이동체공학)

### 코멘트
@PARKMIHE 꽃분류기 주제는 aicoco 팀에게 주어집니다. (from @unizard)
꽃분류기는 네이버와 카카오 모두 서비스하고 있는 모듈이며, 
실제로 머신러닝/딥러닝 기술이 도입되어 있습니다.  비교하면서 진행하시면 도움이 될겁니다.

### 교수님 질문
꽃분류기를 위해 어떤 데이터 셋을 사용 하실 예정이신지?
직접 촬영? 아니면 공개된 데이터셋을 사용하실건가요?
막연한 상황이면 교수님과 티타임!

**Comment by YEJIN325** [comment]
안녕하세요 텀 프로젝트 저희와 같이 하실 2분 구합니다!
현재 이렇게 3명입니다.
지능기전공학부 17011816 서예진
지능기전공학부 17011835 이현지 
지능기전공학부 17011759 최지연
관심 있으신 분 seoyj0325@naver.com으로 연락주세요!

**Comment by unizard** [comment]
@kimkyeongnam @PARKMIHE 
현재 두 팀이 텀프로젝트 주제를 선정완료 했군요. 
근데 두 팀 모두 분류기보다는 영상 검색(Image Retrieval)에 가까운 주제를 선정해서 고민이 되네요.
혹시 두 기술의 차이를 모르고 있다면, 더욱 공부해 보고 결정하세요.
차이를 알고 있음에도 불구하고 문제를 잘 정리해서 풀어볼 생각이라면 교수님에게 설명 부탁드려요.
티타임을 가져도 좋습니다. 🤔

**Comment by BSH0420** [comment]
### [팀5] **주제 : 표정 분류기**

> **팀명 : 페이스타임**

팀장  
-17011780 김연우
팀원  
-17011820 송민주
-17011830 백소현
-17011850 이세정

@BSH0420 
표정분류기를 학습/테스트 데이터를 어디서 어떻게 확보할지 알려줄래요? (@unizard)

**Comment by nhk9680** [comment]
## [팀6] 팀명 : 휴학과 자퇴 사이

## 주제 :  장애물 분류기
> 장애물 검출을 통한 상황 분류
> Situation classification using Obstacle detection

### 팀원 구성
| 이름 | 학과 | 학번 | 비고 |
|:---:|:---:|:---:|:---:|
| **위성민** | 무인이동체공학전공 | 17011877 | **팀장** | 
| 최용호 | 스마트기기공학전공 | 17013253 | 팀원 |
| 권영서 | 무인이동체공학전공 | 17011794 | 팀원 |
| 김남훈 | 스마트기기공학전공 | 17011832 | 팀원 |
| 강산희 | 무인이동체공학전공 | 17011855 | 팀원 |

@nhk9680 
장애물 검출을 통한 상황 분류에 사용할 공개데이터 셋을 먼저 서베이 하여 댓글 남겨주세요.

**Comment by Hongiee2** [comment]
### [팀7] 팀명 : 분류지렸조

**팀원구성**

이름 | 학과 | 학번 | 비고
-- | -- | -- | --
김기홍| 컴퓨터공학과| 14011890| 팀장
김동익| 컴퓨터공학과| 15011037| 팀원
이가경 | 컴퓨터공학과| 15010958 | 팀원
이상민| 무인이동체공학전공 |17013252| 팀원

**Comment by unizard** [comment]
##[팀8] 팀명: ??

**팀원구성**

이름 | 학과 | 학번 | 비고
-- | -- | -- | --
이현지| | | 
최지연| | | 
서예진 | |  |
황정현|  || 
김재형|  ||

**Comment by unizard** [comment]
## [팀9] 팀명: ??

**팀원구성**

이름 | 학과 | 학번 | 비고
-- | -- | -- | --
김남규| | | 
김성빈| | | 
임지윤 | |  |
임세은|  ||

**Comment by unizard** [comment]
## [팀10] 팀명: ??

**팀원구성**

이름 | 학과 | 학번 | 비고
-- | -- | -- | --
황태희| | | 
김태주| | | 
진소라 | |  |
손창우|  ||

**Comment by sorachin** [comment]
## [팀10] 팀명: 작위적인공조
**주제: Meal Planner**

**팀원구성**

이름 | 학과 | 학번 | 비고
-- | -- | -- | --
김태주 | 무인이동체공학 | 17013247 | 팀원
황태희 | 무인이동체공학 | 17013254| 팀원
진소라 | 디지털컨텐츠학과 | 14011195 | 팀원

**Comment by lily0114** [comment]
### [팀8] 팀명: ??????

### 주제: 뉴스 기사의 제목과 내용을 통한 주제 분류기

### 팀원구성
황정현 스마트기기공학 17011827 
서예진 스마트기기공학 17011816 
김재형 스마트기기공학 17011829
최지연 스마트기기공학 17011759 (팀장)
이현지 스마트기기공학 17011835
