### ISSUE TITLE
[참고] Colab 사용하기, Object Detection 따라해보기, Colab으로 장시간 학습하기

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#30]
### 코랩 사용하기
https://zzsza.github.io/data/2018/08/30/google-colab/
제가 서베이 한 곳 중 가장 잘 정리 된 곳이여서 공유합니다. 
혹시 여러분도 정리 잘된 곳을 찾으면 본 이슈에 코멘트로 달아주세요.

### 내용
- 상단 설정
- 구글 드라이브와 Colab 연동
- 구글 드라이브와 로컬 연동
- PyTorch 사용하기
- KoNLPy 설치
- Github 코드를 Colab에서 사용하기
- BigQuery 사용하기
- Matplotlib에서 한글 사용하기
- TensorBoard 사용하기
- JDK 설치하기
- Google Storage에서 파일 읽기
- MNIST on TPU 소스
- Kaggle 연동하기

### 텀플에 도움될 만한 내용
> 필독
- 구글 드라이브와 Colab 연동
- Github 코드를 Colab에서 사용하기
- TensorBoard 사용하기

**Comment by unizard** [comment]
### Colab 단점 극복기
Colab의 가장 큰 단점은 한 세션당  6~8시간만 의 사용을 허용한다는 것입니다.
그러나 이러한 단점은 구글 드라이브에 학습 중간중간 결과물을 저장함으로서, 세션이 끊어진다 하더라도 저장했던 중간 결과물(checkpoint)을 로드하여 학습을 이어 갈 수 있다는 것입니다.
이로써, Colab의 가장 큰 단점은 보완가능하네요. 

https://medium.com/@mukesh.kumar43585/model-checkpoint-google-colab-and-drive-as-persistent-storage-for-long-training-runs-e35ffa0c33d9



### 여러분이 Colab을 통해 사용하는 GPU 사양이 궁금하시나요?
![image](https://user-images.githubusercontent.com/11758940/55286396-71de1f80-53d6-11e9-8f86-12904b5a3b76.png)

와우! 대단하죠? 여러분은 비싼 돈을 주지 않고도 이와 같은 학습가능한 GPU를 사용하고 있는겁니다.
GPU Memory 12G 가 별거 아닌 세상이 왔네요. ㅎㅎ

**Comment by unizard** [comment]
> 아래의 결과를 확인하고 싶으신가요?
> Colab에서 클릭 몇번으로 확인 할 수 있습니다.
> 물론 이미 학습된 모델을 사용해서요!!

[Colab 코드 보러가기](https://colab.research.google.com/drive/1H83ydDNry7rIxksaiXyL_qsDdSyYBqt2)

![image](https://user-images.githubusercontent.com/11758940/55286261-51ad6100-53d4-11e9-94c7-49e829f74635.png)


@All 주말에 심심하신 분들...그냥 Colab Run!! 해보세요~


### 직접 모델 학습 할 수 있나요?

- 제가 직접 테스트까지는 못했지만, 아래와 같이 블로그 포스팅 되어 있네요. 도전 하신 친구는 결과 공유해주세요~
https://medium.com/@moshe.livne/training-tensorflow-for-free-pet-object-detection-api-sample-trained-on-google-collab-c2e65f4a9949

**Comment by zzsza** [comment]
안녕하세요 :) Colab 글을 쓴 사람입니다!
공유해주셔서 감사합니다! 이상하거나 더 궁금하신 내용 있으면 말씀해주세요 :)
