### ISSUE TITLE
TF 체크포인트 불러오기 관련 질문입니다..

### ISSUE THREAD

**Issue by KYUUUW** [unizard/2019.Spring.AI#37]
선형회귀과제인 배추값 문제에서 체크포인트 불러오는데서 문제 생기신분 혹은 문제 해결하신분 있으신가요?

코드 똑같이 따라하고 체크포인트 저장하는 경로만 변경한 코드인데도 불구하고 체크포인트 로딩시

> NotFoundError: Key bias_2 not found in checkpoint
	 [[{{node save_3/RestoreV2}}]]

에러가 생깁니다... ㅜㅜ 같은 이슈 겪으신 분 없나요?

**Comment by unizard** [comment]
아마도 구글드라이브가 안물려 있는거 같은데...
본인의 colab을 공유 모두로 공개해주세요. 그래야 봐줄수 있을듯 합니다.

**Comment by KYUUUW** [comment]
문제 해결했습니다! 감사합니다!!
