### ISSUE TITLE
[공지][과제2] Gradient Descent 알고리즘 python 으로 구현하기

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#38]
### 과제 

아래의 과제2 [베이스 코드](https://colab.research.google.com/drive/1pMCoDVl8ESml2R6DF7EJEHmeHaXh36mF
)를 열고, Gradient Descent 함수를 채우시오.

![image](https://user-images.githubusercontent.com/11758940/55685042-f4458100-598c-11e9-8b2c-0558d86c5922.png)

### 제출 방법
베이스 코드에 Gradient Descent 함수가 채워진 코랩 사본의 링크를 공유설정하여 보내주세요.

**Comment by xown3197** [comment]
이메일 보냈습니다. (무인이동체공학과 김태주)

**Comment by KYUUUW** [comment]
이메일 보냈습니다. (컴퓨터공학과 이규원)

**Comment by Jo-won** [comment]
보냈습니다

**Comment by glee1228** [comment]
이메일 보냈습니다 (디지털콘텐츠학과 이동훈)

**Comment by Namhyunho** [comment]
17013249 이메일 보냈습니다 (무인이동체 남현호)

**Comment by chldydgh4687** [comment]
이메일 보냈습니다.(스마트기기공학 최용호)

**Comment by hahari22** [comment]
이메일 보냈습니다.(무인이동체전공 이상민)

**Comment by sezeom** [comment]
이메일 보냈습니다.(스마트기기 이세정)

**Comment by k-Yeonwoo** [comment]
이메일 보냈습니다 !(스마트기기공학 김연우)

**Comment by ruby-kim** [comment]
이메일 보냈습니다 (소프트웨어학과 김경남)

**Comment by jiin0217** [comment]
이메일 보냈습니다. (디지털콘텐츠학과 유지인)

**Comment by sorachin** [comment]
이메일 보냈습니다 (디컨 진소라)

**Comment by Junuu** [comment]
이메일 보냈습니다.(디지털콘텐츠학과 김준우)

**Comment by rkdogo08** [comment]
이메일 보냈습니다 (무인이동체공학 강산희)

**Comment by Kwon-Yeong-Seo** [comment]
이메일 보냈습니다 (무인이동체공학과 권영서)

**Comment by KakyungLee** [comment]
이메일 보냈습니다(컴퓨터공학과 이가경)

**Comment by Hongiee2** [comment]
이메일 보냈습니다(컴퓨터공학과 김기홍)

**Comment by rjhwang08** [comment]
이메일 보냈습니다. (17011827 스마트기기 황정현)

**Comment by iammiori** [comment]
이메일 보냈습니다 (무인이동체 이미연)

**Comment by zxas14** [comment]
이메일 보냈습니다.(지능기전공학부 김성빈)

**Comment by diakes** [comment]
이메일 보냈습니다 .(컴퓨터공학과 김동익)

**Comment by LIMJIY00N** [comment]
이메일 보냈습니다.(컴퓨터공학과 임지윤)

**Comment by 17011775** [comment]
이메일 보냈습니다(스카트기기 김남규)

**Comment by minju0702** [comment]
이메일 보냈습니다 (무인이동체 송민주)

**Comment by joooooonie** [comment]
이메일 보냈습니다(스마트기기 박준희)

**Comment by BSH0420** [comment]
이메일 보냈습니다. (17011830 백소현)

**Comment by smileeeey** [comment]
이메일 보냈습니다. (16010960 이수민)

**Comment by unizard** [comment]
| 성명 | 제출여부
-- | -- | --
1 | 강산희 | O
2 | 권영서 | O
3 | 김경남 | O
4 | 김기홍 | O
5 | 김남규 | O
6 | 김남훈 | O
7 | 김동익 | O
8 | 김민주 | O
9 | 김성빈 | O
10 | 김연우 | O
11 | 김재형 | O
12 | 김준우 | O
13 | 김지원 | O
14 | 김태주 | O
15 | 김해린 | O
16 | 남현호 | O
17 | 노윤아 | O
18 | 박미희 | O
19 | 박준희 | O
20 | 백소현 | O
21 | 서예진 | O
22 | 손창우 | O
23 | 송민주 | O
24 | 엄단경 | O
25 | 위성민 | O
26 | 유지인 | O
27 | 이가경 | O
28 | 이규원 | O
29 | 이동훈 | O
30 | 이미연 | O
31 | 이상민 | O
32 | 이세미 | O
33 | 이세정 | O
34 | 이수민 | O
35 | 이주혁 | O
36 | 이현지 | O
37 | 임세은 | O
38 | 임지윤 | O
39 | 조원 | O
40 | 진소라 | O
41 | 최용호 | O
42 | 최지연 | O
43 | 한대찬 | O
44 | 황유진 | O
45 | 황정현 | O
46 | 황태희 | O
