### ISSUE TITLE
[공지] 텀 프로젝트 계획서 관련 질의 응답

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#39]
## 텀 프로젝트 계획서

- 계획서 제출 기한: 4/29 (월) 오후 11시 59분
- 계획서 분량: 최소 A4 1장 (장수가 중요한 것이 아니라 아래의 내용을 담을 것)
- 계획서 내용: 
  - 주제 선정의 이유, 
  - 팀원간 명확한 역할 분담, 
  - 프로젝트를 통한 예상 결과물,  
  - 프로젝트에 사용할 데이터 셋, 
  - 기존 연구/개발 조사 결과 등의 내용을 포함
- 추가사항: 공동작업할 github repository를 생성하여 URL 제출

기타 관련 질문은 본 이슈에 댓글로 달아주시길 바랍니다.

**Comment by unizard** [comment]
방향성 잡기 어려울땐 언제든지 찾아오세요.

**Comment by unizard** [comment]
목요일 5시, 6시 예약되어 있습니다.

**Comment by big-chan** [comment]
계획서 자체에 대한 퍼센트가 어느정도 되나요?

**Comment by unizard** [comment]
@big-chan 텀프로젝트관련 성적 비율 및 평가 척도는 계획서 제출이후 공개합니다.

**Comment by hyj378** [comment]
a4용지 1장 분량 넘어도 되나요??

**Comment by unizard** [comment]
@hyj378 네, 가능합니다. 다만, 분량보다 위에 언급된 내용을 담는 것이 중요합니다.

**Comment by socome** [comment]
제안서에 사용할 데이터셋 및 기존 연구 및 개발조사결과등을 링크로 첨부해도 괜찮은지 여쭙고자합니다!!

**Comment by Hongiee2** [comment]
이메일 제출이 맞나요?

**Comment by unizard** [comment]
@socome 간략히 요약 후 자세한 내용은 링크로 제공하셔도 좋습니다.

**Comment by unizard** [comment]
@Hongiee2 네, 이메일 제출 맞습니다.
