### ISSUE TITLE
[공지] 4월 11일 실습 수업 공지

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#40]
금일 실습은 1) Learning Rate 설정방법 2) 데이터 정규화유무에 따른 학습 경향성 파악 입니다.
더불어  우리도!! 손글씨 분류해봅시다.  :)

**Comment by KYUUUW** [comment]
안녕하세요 교수님, 강의 계획을 보면 4/18일까지 주석 작성후 제출이라고 써있는데, 메일로 제출하면 되는건가요??

**Comment by unizard** [comment]
@KYUUUW 네. 평소하시던데로 제출하시면 됩니다.

**Comment by KYUUUW** [comment]
네 제출 완료했습니다!
