### ISSUE TITLE
[참고] 수강생 github 주소

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#41]
순번 | 이름 | URL
-- | -- | --
1 | 강산희 | https://github.com/rkdogo08
2 | 권영서 | https://github.com/Kwon-Yeong-Seo
3 | 김경남 | https://github.com/kimkyeongnam
4 | 김기홍 | https://github.com/Hongiee2
5 | 김남규 | https://github.com/17011775
6 | 김남훈 | https://github.com/nhk9680
7 | 김동익 | https://github.com/diakes
8 | 김민주 | https://github.com/min942773
9 | 김성빈 | https://github.com/zxas14
10 | 김연우 | https://github.com/k-Yeonwoo
11 | 김재형 | https://github.com/kaynsion
12 | 김준우 | https://github.com/Junuu
13 | 김지원 | https://github.com/socome
14 | 김태주 | https://github.com/xown3197
15 | 김해린 |  
16 | 남현호 | https://github.com/Namhyunho
17 | 노윤아 | https://github.com/17011813
18 | 박미희 | https://github.com/PARKMIHE
19 | 박준희 | https://github.com/joooooonie
20 | 백소현 | https://github.com/BSH0420
21 | 서예진 |  
22 | 송민주 | https://github.com/minju0702
23 | 엄단경 | https://github.com/Eomdangyeong
24 | 위성민 |  
25 | 유지인 | https://github.com/jiin0217
26 | 이가경 | https://github.com/KakyungLee
27 | 이규원 | https://github.com/KYUUUW
28 | 이동훈 | https://github.com/glee1228
29 | 이미연 | https://github.com/iammiori
30 | 이상민 | https://github.com/diasy3277
31 | 이세미 |  
32 | 이세정 | https://github.com/sezeom
33 | 이수민 | https://github.com/suimn416
34 | 이주혁 |  https://github.com/zero5two4
35 | 이현지 |  
36 | 임세은 |  
37 | 임지윤 | https://github.com/LIMJIY00N
38 | 조원 | https://github.com/Jo-won
39 | 진소라 | https://github.com/sorachin
40 | 최용호 | https://github.com/chldydgh4687
41 | 최지연 |  
42 | 한대찬 |  
43 | 황유진 | https://github.com/hyj378
44 | 황정현 | https://github.com/rjhwang08
45 | 황태희 | https://github.com/aaliyahee

**Comment by Jooman-Lee** [comment]
34   이주혁 https://github.com/zero5two4

2019년 4월 12일 (금) 오후 8:58, Yukyung Choi <notifications@github.com>님이 작성:

**Comment by ghost** [comment]
https://github.com/LeeSemi
17011862 이세미
