### ISSUE TITLE
[공지] 실습마무리&주석 제출 마감 4월 18일

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#42]
마감일 지켜서 제출해주세요.

**Comment by ruby-kim** [comment]
이메일 보냈습니다 (소프트웨어학과 김경남)

**Comment by KYUUUW** [comment]
이메일 보냈습니다. (컴퓨터공학 이규원)

**Comment by Hongiee2** [comment]
이메일 보냈습니다.(컴퓨터공학 김기홍)

**Comment by sezeom** [comment]
이메일 보냈습니다.(스마트기기 이세정)

**Comment by BSH0420** [comment]
이메일 보냈습니다 (스마트기기 17011830 백소현)

**Comment by iammiori** [comment]
이메일 보냈습니다 (무인이동체 이미연)

**Comment by hahari22** [comment]
이메일 보냈습니다.(무인이동체 이상민)

**Comment by rjhwang08** [comment]
이메일 보냈습니다 (17011827 스마트기기 황정현)

**Comment by Eomdangyeong** [comment]
이메일 보냈습니다 (17011811 엄단경)

**Comment by aaliyahee** [comment]
이메일 보냈습니다 (17013254 황태희)

**Comment by joooooonie** [comment]
이메일 보냈습니다(17011870 박준희)

**Comment by smileeeey** [comment]
이메일 보냈습니다 (16010960 이수민)

**Comment by KakyungLee** [comment]
이메일 보냈습니다.( 컴퓨터공학과 이가경)

**Comment by minju0702** [comment]
이메일 보냈습니다 (17011820 송민주)
