### ISSUE TITLE
[공지] 텀 프로젝트 주제 확정 재확인 요망

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#43]
### 텀 프로젝트 주제 선정 완료

모든 팀이 텀 프로젝트 주제 선정을 마무리 했습니다.
가제로 잡혀 있는 방향을 좀 더 구체화 하여 풀어 쓰셔도 됩니다.
예를들어 랜드마트 분류기 팀의 경우 금일 세종대학교와 세종대 인근 랜드마크 분류기로 명시하였네요. 아주 좋습니다. 

번호 | 팀명 | 주제 | 팀원
-- | -- | -- | --
1 | 소웨지존 | [이모티콘 추천 분류기](https://github.com/hyj378/ArtificialIntelligence) | **김경남**, 김민주, 유지인, 이주혁, 황유진
2 | 인공준희 | [수화분류기](https://github.com/Jo-won/A.I-Term-project) | **조원**, 박준희, 이규원, 이미연, 한대찬
3 | AI대장 | [세종대학교와 세종대 인근 랜드마크 분류기](https://github.com/suimn416/2019.Spring.AI_Leader) | **이수민**, 김지원, 남현호, 이동훈, 김준우
4 | aicoco | [꽃분류기](https://github.com/PARKMIHE/AICOCO) | **박미희**, 이세미, 노윤아, 김해린, 엄단경
5 | 페이스타임 | [표정분류기](https://github.com/facetimee/facetime) | **김연우**, 송민주, 백소현, 이세정
6 | 자퇴와휴학사이 | [장애물분류기](https://github.com/sejongbhaj/SituationClassifier) | **위성민**, 최용호, 권영서, 김남훈, 강산희
7 | 분류지렸죠 | [호흡기 소리 분석을 통한 질병 분류](https://github.com/Hongiee2/Greatest-Classify-Group) | **김기홍**, 김동익, 이가경, 이상민
8 | 기레기통 | [낚시성 기사 분류기](https://github.com/rjhwang08/Clickbait-Classsifier) | **최지연**, 황정현, 서예진, 김재형, 이현지
9 | 리사이클| [재활용품분류기](https://github.com/SEEUNL/Recycle) | **김남규**, 김성빈, 임지윤, 임세은
10 | 작위적인공조 | [음식추천분류기](https://github.com/sorachin/AI_Team10.git) | **김태주**, 황태희, 진소라

**Comment by SEEUNL** [comment]
9조 
팀명 : 리사이클
주제 : 분리수거 분류기

**Comment by unizard** [comment]
### CNN 기반 분류기모델 리더보드 공유
https://kobiso.github.io/Computer-Vision-Leaderboard/imagenet

**Comment by Hongiee2** [comment]
7조
팀명 : 분류지렸조
주제 : 호흡기 소리 분석을 통한 질병 분류

**Comment by suimn416** [comment]
3조 
팀명 : AI대장
주제 : 세종대학교와 세종대 인근  랜드마크 분류기

**Comment by rjhwang08** [comment]
8조 팀명은 **기레기통**으로 정하였으며, 주제는 **낚시성 기사 분류기**로 변경하였습니다.

**Comment by unizard** [comment]
@페이스타임 페이스타임팀의 github URL 부탁드립니다.
