### ISSUE TITLE
[공지] 텀프로젝트 토론 결과 작성

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#44]
금일 토론을 통해 결정된 사항을 요약하여 올려주세요.

### 팀 github URL 공유해주세요

**Comment by PMH2906** [comment]
AICOCO
https://github.com/PARKMIHE/AICOCO
초안 작성 했습니다. 교수님 이메일로 보내겠습니다.

**Comment by lini1634** [comment]
![image](https://user-images.githubusercontent.com/44723287/56336444-5e56f500-61db-11e9-9c63-1720de720b82.png)

**Comment by smileeeey** [comment]
AI대장
https://github.com/suimn416/2019.Spring.AI_Leader
텀 프로젝트 계획서 작성했습니다.

**Comment by Hongiee2** [comment]
분류지렸조
https://github.com/Hongiee2/Greatest-Classify-Group
주제선정이 늦어 계획서 작성까지는 하지 못했습니다.

1. 최종 주제선정
2. 프로젝트 목차작성
3. 관련 작업 자료 검색
4. 팀원간 (대략적인) 역할분담을 진행하였습니다.

**Comment by nhk9680** [comment]
휴학과 자퇴 사이
> https://github.com/sejongbhaj/SituationClassifier
---
계획서 초안 업로드 하였습니다.

@nhk9680 자료 업로드시에는 pdf 가 좋을 것 같습니다. :)

**Comment by ruby-kim** [comment]
**소웨지존**
https://github.com/hyj378/ArtificialIntelligence
계획서 일부작성 및 세부일정에 관한 토론을 했습니다.
계획서는 마감전까지 올리도록 하겠습니다,

**Comment by Seeun-Lim** [comment]
Recycle
https://github.com/SEEUNL/Recycle
4/18일 회의록은 github에 올려놓겠습니다!

**Comment by iammiori** [comment]
**인공준희**
https://github.com/Jo-won/A.I-Term-project/issues/8#issue-434685533
우선 회의록을 올렸고, 계획서는 시험이 끝나는대로 제출하겠습니다

**Comment by rjhwang08** [comment]
**기레기통**
https://github.com/rjhwang08/Clickbait-Classsifier
토론을 거쳐 주제 변경 및 관련 자료 검색을 진행하였습니다.
계획서는 추후에 올리도록 하겠습니다.(팀명 정했습니다!)

**Comment by sorachin** [comment]
### 작위적인공조
https://github.com/sorachin/AI_Team10.git
4월 18일자 회의 : 주제선정, 예상 결과 등 결정하였습니다.

**Comment by unizard** [comment]
1팀 뺴고 모두 제출했네요. 마감합니다.
