### ISSUE TITLE
[공지] 중간고사 시험 관련

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#45]
- 시험시간 80분 (12:00-13:20)
- 총 6문제
- 이론: 5문제 (70점) 
  - 별도의 답안지를 통해 손으로 풉니다.
- 실습: 1문제 (100점 + @최대30점)
- 코멘트
  - 입력데이터에 대한 코드만 제공 
  - 기타 나머지는 본인이 직접 코딩할 수 있도록 연습해야 함
- **필참: 개인노트북 지참**

시험관련 질문은 본 이슈로 가능

(1시간마다 이슈 확인 예정)

**Comment by big-chan** [comment]
+a는 무엇인가요

**Comment by unizard** [comment]
@big-chan 
+@는 주어진 데이터를 이용하여 문제를 해결하면서 "우수한 성능"을 보이는 순서대로 추가점수가 배당됩니다.

**Comment by lini1634** [comment]
기초수학도 시험범위에 포함인가요?

**Comment by unizard** [comment]
@lini1634 시험범위는 배운 모든 내용입니다.

**Comment by Jo-won** [comment]
시험 영어로 나오나요?

**Comment by unizard** [comment]
@Jo-won 

기술용어는 영어로 기억하세요. ex) 과적합 아니죠... overfitting 이죠

**Comment by rjhwang08** [comment]
저번 공지 때 말씀하신 대로 이론 문제는 실습 중간 삽입되는 식으로 나오나요?

**Comment by unizard** [comment]
@rjhwang08 

삽입하는 형태로 진행하다보면, 두마리 토끼를 다 놓치는 학생이 발생할 것으로 생각되어 별도로 분리했습니다.

**Comment by big-chan** [comment]
실습 데이터는 파일 형태로 제공해주시는 건가요?

**Comment by unizard** [comment]
@big-chan 

네 파일 입력에 대한 베이스라인코드는 제공합니다.  걱정안하셔도 됩니다.

**Comment by min942773** [comment]
matplotlib를 이용한 그래프 그리는 방법도 모두 알아둬야하나요?

**Comment by unizard** [comment]
@min942773 본인의 디버깅을 위해 시각화가 필요할 수 있으나 시험의 결과물에 시각화가 들어가 있지는 않습니다.

**Comment by glee1228** [comment]
실습 시, 텐서플로우 사용 가이드도 참고가능한가요?
[https://www.tensorflow.org/guide](https://www.tensorflow.org/guide)
그리고, 가이드 이외에 다른 코드는 참고할 수 없나요?

**Comment by unizard** [comment]
@glee1228 

가이드 참고는 불허합니다.
아래와 같이 **API 메뉴얼**만 사용가능합니다.

https://www.tensorflow.org/api_docs/python/

문법적 오류로 인해 발생하는 문제만을 해결하고자 API 메뉴얼을 공개하는 것입니다. 

@glee1228

Colab은 TAB 키를 이용한 인터프리터 자동완성 기능을 제공합니다.
이를 적극적으로 이용한다면 메뉴얼 사용 횟수를 더욱 줄일 수 있을 것입니다.

**Comment by k-Yeonwoo** [comment]
이론 문제에 대한 답은 모두 영어로 작성해야하나요?

**Comment by min942773** [comment]
mnist 데이터 셋과 같은 영상데이터 처리도 할 줄 알아야 하나요?

**Comment by unizard** [comment]
@k-Yeonwoo 국문/영문 원하시는데로 제출하셔도 됩니다.

**Comment by big-chan** [comment]
시험은 원래 강의실에서 보는건가요?

**Comment by unizard** [comment]
@big-chan 원래 강의실에서 개인 노트북으로 진행합니다. 완전 충전해서 입실하시길 바랍니다.

**Comment by unizard** [comment]
@min942773 어떠한 데이터든 다룰줄 알아야 합니다. 시험범위는 배운데까지입니다.
