### ISSUE TITLE
[참고] 인공신경망 학습 레시피 (번역)

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#49]
여러분이 읽어보면 좋을 것 같은 글을 공유합니다.

[아티클 보기](https://medium.com/@bntejn/%EC%9D%B8%EA%B3%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D-%ED%95%99%EC%8A%B5-%EB%A0%88%EC%8B%9C%ED%94%BC-%EB%B2%88%EC%97%AD-70c5e58341ec?sk=f53042d49fa609d30c80e26f2f7f6b41)

**Comment by Junuu** [comment]
감사합니다
