### ISSUE TITLE
[숙제] 파이썬 실습 숙제 

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#5]
마감시간: 2019년 3월 18일 까지

**Comment by unizard** [comment]
@김해린 김해린 학생 확인되었습니다.

**Comment by ruby-kim** [comment]
이메일로 보냈습니다. (소프트웨어학과 김경남)

**Comment by min942773** [comment]
이메일로 전송했습니다. (소프트웨어학과 김민주)

**Comment by KYUUUW** [comment]
이메일로 전송했습니다. (컴퓨터공학과 이규원)

**Comment by glee1228** [comment]
이메일로 보냈습니다. (디지털콘텐츠학과 이동훈)

**Comment by Junuu** [comment]
이메일로 보냈습니다.(디지털콘텐츠학과 김준우)

**Comment by iammiori** [comment]
이메일로 보냈습니다.(무인이동체전공 이미연)

**Comment by 17011813** [comment]
이메일 보냈습니다(스마트 기기 노윤아)

**Comment by hahari22** [comment]
이메일 보냈습니다.(무인이동체 이상민)

**Comment by sorachin** [comment]
이메일 보냈습니다. (디지털컨텐츠학과 진소라)

**Comment by chldydgh4687** [comment]
2019.AI@rcv.sejong.ac.kr 로 이메일 보냈습니다 (스마트기기 최용호)

**Comment by jiin0217** [comment]
이메일 보냈습니다.(디지털콘텐츠학과 유지인)

**Comment by kaynsion** [comment]
보냈습니다. 17011829 김재형

**Comment by Kwon-Yeong-Seo** [comment]
이메일 보냈습니다. (무인이동체 권영서)

**Comment by diakes** [comment]
이메일 보냈습니다.(컴퓨터공학과 김동익)

**Comment by Eomdangyeong** [comment]
이메일 보냈습니다-엄단경

**Comment by k-Yeonwoo** [comment]
이메일 보냈습니다(스마트기기공학 김연우)

**Comment by KakyungLee** [comment]
이메일 보냈습니다.(컴퓨터공학과 이가경)

**Comment by rjhwang08** [comment]
이메일 보냈습니다. 스마트기기 황정현

**Comment by zxas14** [comment]
이메일 보냈습니다.  스마트기기 김성빈

**Comment by Namhyunho** [comment]
이메일 보냈습니다. 무인이동체 남현호

**Comment by sezeom** [comment]
이메일 보냈습니다. - 스마트기기 이세정

**Comment by hyj378** [comment]
이메일 보냈습니다! -무인이동체 황유진

**Comment by PMH2906** [comment]
무인이동체 박미희 이메일 보냈습니다.

**Comment by Jo-won** [comment]
이메일로 보냈습니다

**Comment by minju0702** [comment]
무인이동체 송민주 이메일 보냈습니다 !

**Comment by joooooonie** [comment]
이메일 보냈습니다-스마트기기 박준희

**Comment by BSH0420** [comment]
스마트기기 백소현 이메일 보냈습니다!

**Comment by aaliyahee** [comment]
이메일 보냈습니다 (무인이동체 황태희)

**Comment by LIMJIY00N** [comment]
이메일 보냈습니다 (컴퓨터공학과 임지윤)

**Comment by Hongiee2** [comment]
이메일 보냈습니다. (컴퓨터공학과 김기홍)

**Comment by nhk9680** [comment]
이메일 보냈습니다. - 스마트기기 김남훈

**Comment by smileeeey** [comment]
16010960 이수민 이메일 보냈습니다

**Comment by 17011775** [comment]
이메일 보냈습니다 (스마트기기 김남규)

**Comment by unizard** [comment]
번호 | 이름 | 제출여부
-- | -- | --
1 | 강산희 | 제출
2 | 권영서 | 제출
3 | 김경남 | 제출
4 | 김기홍 | 제출
5 | 김남규 | 제출
6 | 김남훈 | 제출
7 | 김동익 | 제출
8 | 김민주 | 제출
9 | 김성빈 | 제출
10 | 김연우 | 제출
11 | 김재형 | 제출
12 | 김준우 | 제출
13 | 김지원 | 제출
14 | 김태주 | 제출
15 | 김학주 | 제출
16 | 김해린 | 제출
17 | 남현호 | 제출
18 | 노윤아 | 제출
19 | 박전희 | 제출
20 | 박준희 | 제출
21 | 백소현 | 제출
22 | 서예진 | 제출
23 | 손창우 | 제출
24 | 송민주 | 제출
25 | 위성민 | 제출
26 | 유지인 | 제출
27 | 이가경 | 제출
28 | 이규원 | 제출
29 | 이동훈 | 제출
30 | 이미연 | 제출
31 | 이상민 | 제출
32 | 이세미 | 제출
33 | 이세정 | 제출
34 | 이수민 | 제출
35 | 이주혁 | 제출
36 | 이지연 | 제출
37 | 이현지 | 제출
38 | 임세은 | 제출
39 | 임지윤 | 제출
40 | 조원 | 제출
41 | 진소라 | 제출
42 | 최용호 | 제출
43 | 최지연 | 제출
44 | 한대찬 | 제출
45 | 황유진 | 제출
46 | 황정현 | 제출
47 | 황태희 | 제출

**Comment by KYUUUW** [comment]
컴퓨터공학과 이규원입니다. 이름 중복되어 있습니다! 확인바랍니다!
