### ISSUE TITLE
[공지] 중간 보고서 작성 요청

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#70]
### 작성 및 제출 요령
- 별도의 파일을 제출하지 않습니다.
- 팀 깃애 Readme.txt 파일을 만들어 Markdown 형태로 진행 상황을 정리합니다.
- 본 이슈의 코멘트로 제출 완료되었음을 알려주세요.
- 핵심 포인트
  - 한달 사이 어떤 일들이 진행되었는지..
  - 전체 계획대비 얼마나 진행되었는지..

**Comment by unizard** [comment]
### 중간 보고서 제출 일정 연기
5월 31일 오후 11시 59분으로 연기합니다.

**Comment by yeonnwoo** [comment]
페이스타임 조 제출 완료하였습니다!
https://github.com/facetimee/facetime/blob/master/README.md

**Comment by socome** [comment]
AI대장 조 제출 완료했습니다. 
https://github.com/suimn416/2019.Spring.AI_Leader/blob/master/README.md

**Comment by Hongiee2** [comment]
분류지렸조 제출 완료하였습니다.
https://github.com/Hongiee2/Greatest-Classify-Group/blob/master/README.md

**Comment by ghost** [comment]
AICOCO조 제출 완료하였습니다.
https://github.com/PARKMIHE/AICOCO/blob/master/README.md

**Comment by sorachin** [comment]
작위적인공조 제출 완료하였습니다. 
https://github.com/sorachin/AI_Team10/blob/master/README.md

**Comment by rjhwang08** [comment]
기레기통조 제출 완료했습니다.
https://github.com/rjhwang08/Clickbait-Classsifier/blob/master/README.md

**Comment by min942773** [comment]
소웨지존조 제출 완료했습니다.
https://github.com/hyj378/ArtificialIntelligence/blob/master/README.md

**Comment by unizard** [comment]
| 번호 | 팀명 | 주제 | 중간보고 링크 | 
|:--:|:--:|:--:|:--:|
| 1 | 소웨지존 | 이모티콘분류기 |  [보러가기](https://github.com/hyj378/ArtificialIntelligence/blob/master/README.md) | 
| 2 | 인공준희 | 수화분류기 |  [보러가기]() | 
| 3 | AI대장  | 랜드마크분류기 |  [보러가기](https://github.com/suimn416/2019.Spring.AI_Leader/blob/master/README.md) | 
| 4 | aicoco | 꽃분류기 |  [보러가기](https://github.com/PARKMIHE/AICOCO/blob/master/README.md) | 
| 5 | 페이스타임 | 표정분류기 |  [보러가기](https://github.com/facetimee/facetime/blob/master/README.md) | 
| 6 | 자퇴와휴학사이 | 장애물분류기 |  [보러가기]() | 
| 7 | 분류지렷죠 | 질병분류 |  [보러가기](https://github.com/Hongiee2/Greatest-Classify-Group/blob/master/README.md) | 
| 8 | 기레기통 | 낚시성기사분류기 |  [보러가기](https://github.com/rjhwang08/Clickbait-Classsifier/blob/master/README.md) | 
| 9 | 리사이클 | 재활용분류기 |  [보러가기]() | 
| 10 | 작위적인공조 | 음식추천분류기 |  [보러가기](https://github.com/sorachin/AI_Team10/blob/master/README.md) |

**Comment by 17011775** [comment]
리사이클조 제출 완료했습니다.
https://github.com/SEEUNL/Recycle/blob/master/README.md

**Comment by nhk9680** [comment]
자퇴와휴학사이 제출 완료했습니다.
https://github.com/sejongbhaj/SituationClassifier/blob/master/README.md

**Comment by unizard** [comment]
| 번호 | 팀명 | 주제 | 중간보고 링크 | 
|:--:|:--:|:--:|:--:|
| 1 | 소웨지존 | 이모티콘분류기 |  [보러가기](https://github.com/hyj378/ArtificialIntelligence/blob/master/README.md) | 
| 2 | 인공준희 | 수화분류기 |  [보러가기](https://github.com/Jo-won/A.I-Term-project) | 
| 3 | AI대장  | 랜드마크분류기 |  [보러가기](https://github.com/suimn416/2019.Spring.AI_Leader/blob/master/README.md) | 
| 4 | aicoco | 꽃분류기 |  [보러가기](https://github.com/PARKMIHE/AICOCO/blob/master/README.md) | 
| 5 | 페이스타임 | 표정분류기 |  [보러가기](https://github.com/facetimee/facetime/blob/master/README.md) | 
| 6 | 자퇴와휴학사이 | 장애물분류기 |  [보러가기](https://github.com/sejongbhaj/SituationClassifier/blob/master/README.md) | 
| 7 | 분류지렷죠 | 질병분류 |  [보러가기](https://github.com/Hongiee2/Greatest-Classify-Group/blob/master/README.md) | 
| 8 | 기레기통 | 낚시성기사분류기 |  [보러가기](https://github.com/rjhwang08/Clickbait-Classsifier/blob/master/README.md) | 
| 9 | 리사이클 | 재활용분류기 |  [보러가기](https://github.com/SEEUNL/Recycle/blob/master/README.md) | 
| 10 | 작위적인공조 | 음식추천분류기 |  [보러가기](https://github.com/sorachin/AI_Team10/blob/master/README.md) |

**Comment by joooooonie** [comment]
인공준희 조 제출 완료했습니다
https://github.com/Jo-won/A.I-Term-project/blob/master/README.md

**Comment by unizard** [comment]
인공준희조는 이메일로 제출했기에 대신 기록을 남깁니다.
<img width="463" alt="스크린샷 2019-05-31 오후 11 59 58" src="https://user-images.githubusercontent.com/11758940/58714698-3aa0e480-8400-11e9-87c9-a1c617eb188a.png">

**Comment by unizard** [comment]
## 모든 조 제출 완료

| 번호 | 팀명 | 주제 | 중간보고 링크 | 
|:--:|:--:|:--:|:--:|
| 1 | 소웨지존 | 이모티콘분류기 |  [보러가기](https://github.com/hyj378/ArtificialIntelligence/blob/master/README.md) | 
| 2 | 인공준희 | 수화분류기 |  [보러가기](https://github.com/Jo-won/A.I-Term-project) | 
| 3 | AI대장  | 랜드마크분류기 |  [보러가기](https://github.com/suimn416/2019.Spring.AI_Leader/blob/master/README.md) | 
| 4 | aicoco | 꽃분류기 |  [보러가기](https://github.com/PARKMIHE/AICOCO/blob/master/README.md) | 
| 5 | 페이스타임 | 표정분류기 |  [보러가기](https://github.com/facetimee/facetime/blob/master/README.md) | 
| 6 | 자퇴와휴학사이 | 장애물분류기 |  [보러가기](https://github.com/sejongbhaj/SituationClassifier/blob/master/README.md) | 
| 7 | 분류지렷죠 | 질병분류 |  [보러가기](https://github.com/Hongiee2/Greatest-Classify-Group/blob/master/README.md) | 
| 8 | 기레기통 | 낚시성기사분류기 |  [보러가기](https://github.com/rjhwang08/Clickbait-Classsifier/blob/master/README.md) | 
| 9 | 리사이클 | 재활용분류기 |  [보러가기](https://github.com/SEEUNL/Recycle/blob/master/README.md) | 
| 10 | 작위적인공조 | 음식추천분류기 |  [보러가기](https://github.com/sorachin/AI_Team10/blob/master/README.md) |
