### ISSUE TITLE
[공유] 데이터 사이언스 공부법

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#76]
> 딥놀 이라는 팀이 이런 동영상을 공개했네요? 가볍게 한번 보시죠.

https://www.youtube.com/watch?v=aV8vG7xHPIQ&list=PLlCyphvU1f9DBoavqYMD3qhk6Req-e7wG

**Comment by unizard** [comment]
Q. 데이터 사이언스란 무엇일까? 1:07
Q. 데이터 사이언스는 언제 어떻게 시작했을까? 2:23
Q. 데이터 사이언스와 관련된 직업은 어떤 것들이 있을까? 4:13
- 데이터 분석가란? 4:38
- 데이터 엔지니어란? 4:59
- 데이터 사이언티스트란? 5:43
- 데이터 사이언티스트와 딥러닝 & 머신러닝 전문가와의 차이점은? 7:46

**Comment by glee1228** [comment]
좋은 영상 공유해주셔서 감사합니다!
