### ISSUE TITLE
[조사] 6/13(목),  6/24(월) 선택

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#78]
6/13일 목요일과 6/24일 월요일중 많은 학생이 선호하는 날로 텀프로젝트 발표평가를 진행합니다.
6/13 목요일은 6:30-9:30 
6/24 월요일은 6:00-9:00 

24일 출국하는 학생들의 경우 불참해도 좋습니다. 단, 해외출국을 증빙하고 팀내 다른 팀원이 해당 내용을 숙지하고 있으면 됩니다.

그럼, 본 이슈 댓글로 의견주세요.

### 월요일 시간 수정
- 계절학기 학생들을 고려하여 월요일도 6:00-9:00 로 변경함

**Comment by Hongiee2** [comment]
저는 6/13일이 좋습니다. 24일의 경우 계절학기 듣는 학생들도 있을 것 같아요!

@Hongiee2 시간을 옮겼으니, 계절학기도 가능!

**Comment by 17011813** [comment]
저도 13일이 더 좋습니다~!

**Comment by hahari22** [comment]
저도 13일이 좋습니다!

**Comment by k-Yeonwoo** [comment]
저도 13일이요!!!

**Comment by smileeeey** [comment]
저도 13일이 좋습니다!!

**Comment by rjhwang08** [comment]
교수님 저는 24일에 꼭 하고 싶습니다!!!

**Comment by lily0114** [comment]
저는 24일이 좋습니다!

**Comment by ruby-kim** [comment]
저는 24일이 좋아요~ :-)

**Comment by joooooonie** [comment]
24일이 좋습니다 !

**Comment by iammiori** [comment]
발표준비를 위해 24일이 좋을거 같습니다.

**Comment by KYUUUW** [comment]
24일 좋습니다

**Comment by diakes** [comment]
저는 13일이 좋습니다!

**Comment by unizard** [comment]
13일 6명, 24일 6명

**Comment by big-chan** [comment]
저는 13일이 좋습니다

**Comment by jiyeon5** [comment]
저는 24일이 좋습니다!

**Comment by kaynsion** [comment]
24일이 좋습니다

**Comment by LIMJIY00N** [comment]
24일이 좋습니다

**Comment by YEJIN325** [comment]
24일이 좋습니다!

**Comment by Seeun-Lim** [comment]
13일이 좋습니다!

**Comment by socome** [comment]
12일에 모두 일괄로 제출하고 각자가 가능한 날에 나눠 진행하는것도 좋을것같습니다.

**Comment by unizard** [comment]
현재 13일 8명, 24일 10명 입니다.
결과는 의견이 많은 쪽으로 결정납니다.

**Comment by KakyungLee** [comment]
13일이 좋습니다.

**Comment by 17011775** [comment]
24일이 좋습니다!

**Comment by hyj378** [comment]
24일이 좋습니다!

**Comment by zxas14** [comment]
24일이 좋습니다

**Comment by k-Yeonwoo** [comment]
24일이 좋아요

**Comment by sorachin** [comment]
24일이 좋습니다

**Comment by xown3197** [comment]
24일 희망합니다

**Comment by Junuu** [comment]
24일 희망합니다.

**Comment by Namhyunho** [comment]
24일이 좋습니다

**Comment by min942773** [comment]
24일이 좋습니다!

**Comment by nhk9680** [comment]
24일 희망합니다.

**Comment by ghost** [comment]
24일 희망합니다

**Comment by glee1228** [comment]
24일 희망합니다!

**Comment by socome** [comment]
24일 희망합니다.

**Comment by Jo-won** [comment]
24일이 좋습니다!

**Comment by rkdogo08** [comment]
13일 희망합니다.

**Comment by jiin0217** [comment]
13일이 좋습니다

**Comment by Kwon-Yeong-Seo** [comment]
24일이 좋습니다

**Comment by lini1634** [comment]
24일

**Comment by PMH2906** [comment]
24일이 좋아요

**Comment by BSH0420** [comment]
24일이 좋습니다!

**Comment by unizard** [comment]
24일로 결정되었기에 클로즈 합니다.
