### ISSUE TITLE
4일차 실습 참고 사항 입니다. 

### ISSUE THREAD

**Issue by Namhyunho** [unizard/2019.Spring.AI#8]
colab에서 실습 하실 때  

import matplotlib.pyplot as plt
import numpy as np

작성하시고  실습 하시면 됩니다.

**Comment by unizard** [comment]
@Namhyunho 교수님의 실수 잡아줘서 고맙!

**Comment by ruby-kim** [comment]
**mean** 을 구할 때는
import seaborn as sns

seaborn 시각화 패키지를 임포트 해주세요~~ :-)

**Comment by ruby-kim** [comment]
**map** 을 할 때는
import scipy as sp

scipy, 수치해석기능을 제공하는 패키지를 임포트 해주세요!
