### ISSUE TITLE
[공지] Deep Learning 책 스터디 수요조사

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#86]
2019학년도 여름방학 중 Deep Learning 책 스터디에 관심있는 학생들의 수요조사를 실시합니다.

스터디책: https://www.deeplearningbook.org/
스터디주기: 1회/주
스터디방식: 함께 결정

본 이슈의 댓글로 의사표현 부탁드립니다~~~~

**Comment by hyj378** [comment]
관심있습니다!

**Comment by KYUUUW** [comment]
관심있습니다!

**Comment by sezeom** [comment]
관심있습니다!

**Comment by hahari22** [comment]
저도 관심있습니다!

**Comment by zxas14** [comment]
관심있습니다!

**Comment by diakes** [comment]
관심있습니다!

**Comment by ruby-kim** [comment]
관심있습니다!!

**Comment by xown3197** [comment]
저도 관심있습니다.

**Comment by glee1228** [comment]
관심있습니다 교수님!

**Comment by rjhwang08** [comment]
관심있습니다!

**Comment by 17011775** [comment]
관심있습니다!

**Comment by unizard** [comment]
@hyj378
@KYUUUW
@sezeom
@diasy3277
@zxas14
@diakes
@kimkyeongnam 
@xown3197
@glee1228 
@rjhwang08 
@17011775

운영방식은 PR12와 같이 할까 합니다. 
아래의 주소에서 비디오 한번씩 보고 의견들 주세요.
https://sites.google.com/rcv.sejong.ac.kr/airesearch/ai-%EA%B3%B5%EB%B6%80/level-iv?authuser=0

**Comment by socome** [comment]
참여희망합니다.

**Comment by Namhyunho** [comment]
참여희망합니다

**Comment by Jooman-Lee** [comment]
하고싶습니다!

**Comment by nhk9680** [comment]
참여 희망합니다~!

**Comment by big-chan** [comment]
희망합니다~~

**Comment by jiin0217** [comment]
참여 희망합니다!

**Comment by Jo-won** [comment]
희망합니다~!

**Comment by chldydgh4687** [comment]
참여 희2망합니다~!

**Comment by unizard** [comment]
19명? 응? 너무 많은데;;
