### ISSUE TITLE
[공지] 텀 프로젝트 일정 재공지

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#92]
## 최종 일정 공지
- 반드시 일정 재확인 부탁드립니다. <br>
![image](https://user-images.githubusercontent.com/11758940/58622210-0f39cf00-8306-11e9-9707-0dfc868ce5c8.png)

**Comment by chldydgh4687** [comment]
확인햇습니다~

**Comment by Hongiee2** [comment]
교수님! 텀 발표 기간이 다가와서 질문드립니다. 발표시 팀원 모두가 참여해야하는지와 발표 시간이 궁금합니다.

**Comment by unizard** [comment]
네 전원참석입니다. 발표시간은 6시부터이며 발표차례는 제가 결정합니다.
