### ISSUE TITLE
[공지] GPU 서버 빌려드립니다.

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#94]
금일 교수님 연구실로 2080TI 4장이 달려있는 서버를 공급받았습니다.
따라서 여러분의 텀플 기간동안(~6/14) 필요한 팀에 한해 카드 한장씩 빌려드리까 합니다.
4팀 선착순으로 받습니다. 
댓글 달아주세요.

**Comment by min942773** [comment]
1조 필요합니다! 감사합니다☺️

**Comment by unizard** [comment]
@min942773 세팅완료했으며, 팀깃에 관련 정보를 남겨두었으니 확인바랍니다.

**Comment by Seeun-Lim** [comment]
리사이클 조 신정합니다~ 감사합니다!!

**Comment by unizard** [comment]
@SEEUNL 멘션보면 교수님한테 문자 혹은 카톡
