### ISSUE TITLE
[수요조사] SW 고교 멘토링 프로그램 & AI 고교 멘토링 프로그램

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#95]
##  SW 고교 멘토링 프로그램 & AI 고교 멘토링 프로그램

안녕하세요. 여러분, 최유경입니다.

세종대학교 소프트웨어융합대학은 학기마다 고등학교 동아리를 방문하여 SW 기초 교육 멘토링을 담당하는 프로그램을 운영하고 있습니다.
본 프로그램은 세종대 학생 3인 한팀을 이루어 C언어, 파이썬, 아두이노 와 같은 교육을 담당하는 것입니다.
> [관련링크](https://github.com/swmentoring/)

최근 AI와 관련된 사회적 니즈가 늘어나면서 각학교로부터 AI 관련 교육 요청이 늘고 있습니다.
이에 다음학기 멘토링 모집에 참고할 수요조사를 실시 하고자 합니다.

여러분이 한학기 동안 배운 내용의 일부를 고등학교에 방문하여 약 10회에 거쳐 
간단 강의 + Colab 실습하는 형태의 커리큘럼으로 AI Mentorting 에 관심있는 친구들이 있으면 답글 달아주세요.
아! 당연히 본 프로그램은 봉사점수 혹은 조교비를 지원받습니다. :)

## 한줄요약
AI 고교멘토링 프로그램에 관심있으신분 댓글! 고고

**Comment by min942773** [comment]
관심있습니다!

**Comment by Hongiee2** [comment]
저도 관심있습니다!

**Comment by ruby-kim** [comment]
시간이 된다면 저도 참여하고 싶습니다! :-)

**Comment by socome** [comment]
관심있습니다.
