### ISSUE TITLE
[공지] 개별 시험 일정을 정해주세요.. (선착순) 

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.AI#96]
https://docs.google.com/spreadsheets/d/1i8z2Uf-sA0iXWNZksQSajWq_qeniq2XJP4RBJPrkock/edit?usp=sharing

구글 독에 작성하고, 혹시 모를 사태에 대비하여 본 이슈에도 작성요망

**Comment by rjhwang08** [comment]
17011827 황정현 20일 2:00-2:10에 하고 싶습니다.

**Comment by Hongiee2** [comment]
14011890 김기홍 18일 5:00 - 5:10에 하고 싶습니다.

**Comment by Hongiee2** [comment]
교수님 스프레드시트 보기전용이라 타이핑이 안돼요ㅎㅎ

**Comment by hahari22** [comment]
17013252 이상민 18일 5:10 - 5:20 에 하고 싶습니다!

**Comment by unizard** [comment]
황정현, 김기홍, 이상민 반영완료

**Comment by KakyungLee** [comment]
15010958 이가경 20일  6시 20분에 하고싶습니다.

**Comment by ghost** [comment]
17011862 이세미 20일 4시 30분에 하고 싶습니다.

**Comment by lini1634** [comment]
17011755 김해린 18일 4시 10분 하고싶습니다

**Comment by min942773** [comment]
17011660 김민주 18일 6시에 하고 싶습니다.

**Comment by PMH2906** [comment]
17011757 박미희 18일 4시 20분에 하고 싶습니다.

**Comment by Eomdangyeong** [comment]
17011811 엄단경 18일 4시에 하고 싶습니다

**Comment by 17011775** [comment]
17011775 김남규 20일 6시에 하고 싶습니다

**Comment by zxas14** [comment]
17011867 김성빈 20일 3시 20분에 하고 싶습니다.

**Comment by 17011813** [comment]
17011813 노윤아 20일 2시 30분 작성했습니다.

**Comment by iammiori** [comment]
17011879 이미연 18일 5:20 ~ 5:30 하고싶습니다

**Comment by diakes** [comment]
15011037 김동익 18일 2시에 하고 싶습니다

**Comment by Kwon-Yeong-Seo** [comment]
17011794 권영서 18일 5:50-6:00 작성했습니다

**Comment by ruby-kim** [comment]
17011654 김경남 20일 03:10~03:20 작성했습니다!

**Comment by nhk9680** [comment]
17011832 김남훈 20일 5:50-6:00 작성했습니다

**Comment by sorachin** [comment]
진소라 18일 화요일 4시 40분 ~ 4시 50분 작성했습니다.

**Comment by smileeeey** [comment]
16010960 이수민 18일 화요일 2시 40분~ 2시 50분 작성했습니다

**Comment by socome** [comment]
14011615 김지원 18일 3:30~3:40 작성했습니다.

**Comment by hyj378** [comment]
18011756 황유진 20일 6:10-6:20 작성했습니다.

**Comment by jiin0217** [comment]
16011191 유지인 18일 2:10-2:20분 작성했습니다.

**Comment by Jooman-Lee** [comment]
17011683 이주혁 18일 3:10-3:20분 작성했습니다.

**Comment by big-chan** [comment]
17011883 한대찬 20일 4:50~5:00 작성했습니다.

**Comment by Jo-won** [comment]
17011822 조원 20일 5:00-5:10 작성했습니다.

**Comment by KYUUUW** [comment]
15010815 이규원 05:10 ~ 05:20 작성했습니다.

**Comment by jiyeon5** [comment]
17011759 최지연 20일 2:10-2:20 작성했습니다.

**Comment by Namhyunho** [comment]
17013249 남현호 18일 06:20 ~ 06:30 작성하였습니다

**Comment by lily0114** [comment]
17011835 이현지 20일 2:20-2:30 작성했습니다

**Comment by chldydgh4687** [comment]
17013253 최용호 20일  5:40-5:50 작성했습니다.

**Comment by YEJIN325** [comment]
17011816 서예진 20일 3:30-3:40 작성했습니다.

**Comment by rkdogo08** [comment]
17011855 강산희 20일 5:20-5:30 작성했습니다.

**Comment by Seeun-Lim** [comment]
17011043 임세은 20일 4:20~4:30분 작성했습니다!

**Comment by Junuu** [comment]
16011170 김준우 18일 1:30-1:40분 작성했습니다.

**Comment by glee1228** [comment]
18일 14:50~15:00 작성했습니다

**Comment by yeonnwoo** [comment]
17011780 김연우 18 일 5시 30분-5시40분 작성했습니다

**Comment by minju0702** [comment]
17011820 송민주 18일 2:30-2:40 작성했습니다

**Comment by yeonnwoo** [comment]
17011830 백소현 20일 1:30~1:40 작성했습니다.

**Comment by sezeom** [comment]
17011850 이세정 20일 1:50~2:00 작성했습니다.

**Comment by aaliyahee** [comment]
17013254 황태희 20일 2:40-2:50 작성 했습니다

**Comment by xown3197** [comment]
17013247 김태주 20일 5:30-5:40 작성했습니다.

**Comment by unizard** [comment]
모든 사람이 작성을 완료하여 클로즈 합니다.
